version: '3.4'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka-node
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "unified.metrics.json:3:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  influxdb:
      image: influxdb:latest
      container_name: influxdb
      ports:
          - "8086:8086"
      volumes:
          #- ${PWD}/influxdb:/var/lib/influxdb
          - ${PWD}/influxdb.conf:/etc/influxdb/influxdb.conf:ro

  telegraf:
      image: telegraf:latest
      container_name: telegraf
      volumes:
          - ${PWD}/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      ports:
          - "8092:8092/udp"
          - "8094:8094"
          - "8125:8125/udp"
