version: '3.4'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka-node
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      # topic string structure is "topic-name:partition:replica"
      KAFKA_CREATE_TOPICS: "unified.metrics.json:3:1,uim.metrics.json:3:1,zenoss.metrics.json:3:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  localhost:
      image: influxdb:latest
      container_name: influxdb
      ports:
          - "8086:8086"
      volumes:
          - ${PWD}/influxdb.conf:/etc/influxdb/influxdb.conf:ro

  redis:
      image: 'bitnami/redis:latest'
      container_name: redis
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      ports:
        - '6379:6379'
